pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_REGION            = 'us-west-2'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/TomMLe/changing-room.git'
            }
        }

        stage('Verify Files') {
            steps {
                dir('infra') {
                    sh 'ls -l'
                }
            }
        }

        stage('Debug Directory') {
            steps {
                sh 'pwd'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('infra') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
    }

    post {
        always {
            dir('infra') {
                archiveArtifacts artifacts: '**/*.tfstate', allowEmptyArchive: true
            }
            cleanWs()
        }
    }
}
